// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types













../../../frontend/app/page.js../../../frontend/app/api/dashboard/route.js../../../frontend/app/layout.js